// SPDX-License-Identifier: PMPL-1.0-or-later
// Copyright (c) 2026 Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
//
// CMake build file generator for halideiser.
//
// Generates a CMakeLists.txt that:
//   1. Finds the Halide package
//   2. Adds a Halide generator from the generated C++ source
//   3. Calls halide_library() to compile the generator for the target
//   4. Builds a runner executable linked against the generated library

use crate::abi::HardwareTarget;
use crate::manifest::Manifest;

/// Generate a complete CMakeLists.txt for building the Halide pipeline.
///
/// The generated CMake file uses Halide's CMake integration (HalideHelpers.cmake)
/// which provides `add_halide_generator` and `add_halide_library` macros.
pub fn generate_cmake(manifest: &Manifest) -> String {
    let name = &manifest.project.name;
    let target = &manifest.target.arch;
    let halide_target = halide_target_string(target);

    let mut cmake = String::with_capacity(2048);

    // Header.
    cmake.push_str("# Auto-generated by halideiser — DO NOT EDIT\n");
    cmake.push_str("# SPDX-License-Identifier: PMPL-1.0-or-later\n\n");
    cmake.push_str("cmake_minimum_required(VERSION 3.22)\n");
    cmake.push_str(&format!("project({name} LANGUAGES CXX)\n\n"));

    // C++ standard.
    cmake.push_str("set(CMAKE_CXX_STANDARD 17)\n");
    cmake.push_str("set(CMAKE_CXX_STANDARD_REQUIRED ON)\n\n");

    // Find Halide.
    cmake.push_str("# Find Halide installation\n");
    cmake.push_str("find_package(Halide REQUIRED)\n\n");

    // Halide target configuration.
    cmake.push_str(&format!("# Target: {}\n", target,));
    cmake.push_str(&format!("set(HALIDE_TARGET \"{}\")\n\n", halide_target,));

    // Generator executable.
    cmake.push_str("# Build the Halide generator\n");
    cmake.push_str(&format!(
        "add_executable({name}_generator {name}_generator.cpp)\n"
    ));
    cmake.push_str(&format!(
        "target_link_libraries({name}_generator PRIVATE Halide::Generator)\n\n"
    ));

    // Halide library (runs the generator to produce the AOT-compiled pipeline).
    cmake.push_str("# Run generator to produce AOT library\n");
    cmake.push_str(&format!("add_halide_library({name}_halide\n"));
    cmake.push_str(&format!("    FROM {name}_generator\n"));
    cmake.push_str(&format!("    GENERATOR {name}_generator\n"));
    cmake.push_str("    TARGETS ${{HALIDE_TARGET}}\n");

    // Add feature flags based on target.
    let features = halide_feature_flags(target, manifest.target.vectorize);
    if !features.is_empty() {
        cmake.push_str(&format!("    FEATURES {}\n", features,));
    }
    cmake.push_str(")\n\n");

    // Runner executable.
    cmake.push_str("# Build the runner executable\n");
    cmake.push_str(&format!(
        "add_executable({name}_runner {name}_runner.cpp)\n"
    ));
    cmake.push_str(&format!("target_link_libraries({name}_runner\n"));
    cmake.push_str(&format!("    PRIVATE {name}_halide Halide::ImageIO)\n\n"));

    // Install rules.
    cmake.push_str("# Install\n");
    cmake.push_str(&format!("install(TARGETS {name}_runner DESTINATION bin)\n"));

    cmake
}

/// Return the Halide target string for the given hardware target.
fn halide_target_string(target: &HardwareTarget) -> String {
    target.to_string()
}

/// Return Halide feature flags for the target.
/// These enable specific SIMD/compute features beyond the base target.
fn halide_feature_flags(target: &HardwareTarget, vectorize: bool) -> String {
    let mut features = Vec::new();

    match target {
        HardwareTarget::X86 => {
            if vectorize {
                features.push("sse41");
                features.push("avx");
                features.push("avx2");
                features.push("fma");
            }
        }
        HardwareTarget::Arm => {
            if vectorize {
                features.push("arm_dot_prod");
            }
        }
        HardwareTarget::Cuda => {
            features.push("cuda_capability_61");
        }
        HardwareTarget::Opencl => {
            features.push("cl_doubles");
        }
        HardwareTarget::Wasm => {
            if vectorize {
                features.push("wasm_simd128");
            }
        }
    }

    features.join(" ")
}

/// Generate build commands as a shell script (alternative to CMake).
/// Useful for environments without CMake or for CI scripts.
pub fn generate_build_script(manifest: &Manifest) -> String {
    let name = &manifest.project.name;
    let target = &manifest.target.arch;
    let halide_target = halide_target_string(target);

    let mut script = String::with_capacity(1024);
    script.push_str("#!/usr/bin/env bash\n");
    script.push_str("# Auto-generated by halideiser — DO NOT EDIT\n");
    script.push_str("# SPDX-License-Identifier: PMPL-1.0-or-later\n");
    script.push_str("set -euo pipefail\n\n");

    script.push_str("HALIDE_DIR=\"${HALIDE_DIR:-/usr/local}\"\n");
    script.push_str(&format!("TARGET=\"{}\"\n\n", halide_target));

    // Compile generator.
    script.push_str("echo \"Compiling generator...\"\n");
    script.push_str(&format!(
        "g++ -std=c++17 -fno-rtti -I${{HALIDE_DIR}}/include \\\n\
         \x20   {name}_generator.cpp \\\n\
         \x20   -L${{HALIDE_DIR}}/lib -lHalide -lpthread -ldl \\\n\
         \x20   -o {name}_gen\n\n"
    ));

    // Run generator to produce AOT library.
    script.push_str("echo \"Running generator for target: ${TARGET}\"\n");
    script.push_str(&format!(
        "./{name}_gen -g {name}_generator -o . target=${{TARGET}}\n\n"
    ));

    // Compile runner.
    script.push_str("echo \"Compiling runner...\"\n");
    script.push_str(&format!(
        "g++ -std=c++17 -I${{HALIDE_DIR}}/include -I. \\\n\
         \x20   {name}_runner.cpp {name}_generator.a \\\n\
         \x20   -L${{HALIDE_DIR}}/lib -lHalide -lpthread -ldl -ljpeg -lpng \\\n\
         \x20   -o {name}_runner\n\n"
    ));

    script.push_str(&format!("echo \"Build complete: ./{name}_runner\"\n"));

    script
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::manifest::parse_manifest;

    #[test]
    fn test_generate_cmake_x86() {
        let toml_str = r#"
[project]
name = "cmake_test"

[[stages]]
name = "blur"
operation = "blur"

[target]
arch = "x86"
vectorize = true
parallelize = true

[pipeline]
input-format = "png"
output-format = "png"
"#;
        let m = parse_manifest(toml_str).unwrap();
        let cmake = generate_cmake(&m);
        assert!(cmake.contains("cmake_minimum_required"));
        assert!(cmake.contains("find_package(Halide REQUIRED)"));
        assert!(cmake.contains("cmake_test_generator"));
        assert!(cmake.contains("cmake_test_runner"));
        assert!(cmake.contains("avx2"));
    }

    #[test]
    fn test_generate_cmake_cuda() {
        let toml_str = r#"
[project]
name = "cuda_pipe"

[[stages]]
name = "blur"
operation = "blur"

[target]
arch = "cuda"

[pipeline]
input-format = "raw"
output-format = "raw"
"#;
        let m = parse_manifest(toml_str).unwrap();
        let cmake = generate_cmake(&m);
        assert!(cmake.contains("host-cuda"));
        assert!(cmake.contains("cuda_capability_61"));
    }

    #[test]
    fn test_generate_cmake_wasm() {
        let toml_str = r#"
[project]
name = "wasm_pipe"

[[stages]]
name = "threshold"
operation = "threshold"
value = 128.0

[target]
arch = "wasm"
vectorize = true

[pipeline]
input-format = "png"
output-format = "png"
"#;
        let m = parse_manifest(toml_str).unwrap();
        let cmake = generate_cmake(&m);
        assert!(cmake.contains("wasm-32-wasmrt"));
        assert!(cmake.contains("wasm_simd128"));
    }

    #[test]
    fn test_generate_build_script() {
        let toml_str = r#"
[project]
name = "script_test"

[[stages]]
name = "edge"
operation = "edge-detect"

[target]
arch = "arm"

[pipeline]
input-format = "raw"
output-format = "png"
"#;
        let m = parse_manifest(toml_str).unwrap();
        let script = generate_build_script(&m);
        assert!(script.contains("#!/usr/bin/env bash"));
        assert!(script.contains("script_test_gen"));
        assert!(script.contains("script_test_runner"));
    }

    #[test]
    fn test_feature_flags_none_when_no_vectorize() {
        let flags = halide_feature_flags(&HardwareTarget::X86, false);
        assert!(flags.is_empty());
    }
}
