// SPDX-License-Identifier: PMPL-1.0-or-later
// Copyright (c) 2026 Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
//
// Halide C++ code generator for halideiser.
//
// Generates two C++ files:
//   1. <name>_generator.cpp — Halide::Generator subclass with algorithm + schedule
//   2. <name>_runner.cpp    — standalone runner that uses the generated pipeline
//
// The generator uses Halide's Generator infrastructure so it can be compiled
// with `GenGen` and produce static libraries / object files for any target.

use crate::abi::{HalideOperation, HardwareTarget, PixelType, SchedulePrimitive};
use crate::codegen::parser::{ResolvedPipeline, ResolvedStage};
use crate::manifest::Manifest;

// ---------------------------------------------------------------------------
// Generator C++ source
// ---------------------------------------------------------------------------

/// Generate the complete Halide generator C++ source file.
/// This produces a `Halide::Generator` subclass that defines the algorithm
/// and schedule for the entire pipeline.
pub fn generate_halide_generator(manifest: &Manifest, pipeline: &ResolvedPipeline) -> String {
    let name = &manifest.project.name;
    let pixel_type = &manifest.pipeline.bit_depth;
    let target = &manifest.target.arch;

    let mut code = String::with_capacity(4096);

    // File header.
    code.push_str(&format!(
        "// Auto-generated by halideiser v{} — DO NOT EDIT\n",
        env!("CARGO_PKG_VERSION")
    ));
    code.push_str("// SPDX-License-Identifier: PMPL-1.0-or-later\n");
    code.push_str(&format!(
        "// Pipeline: {} ({} stages, target: {})\n\n",
        name,
        pipeline.stages.len(),
        target,
    ));

    // Includes.
    code.push_str("#include \"Halide.h\"\n");
    code.push_str("#include <cmath>\n\n");
    code.push_str("using namespace Halide;\n\n");

    // Generator class.
    code.push_str(&format!(
        "class {name}Generator : public Generator<{name}Generator> {{\n"
    ));
    code.push_str("public:\n");

    // Input buffer.
    code.push_str(&format!(
        "    Input<Buffer<{pixel_t}, 3>> input{{\"input\"}};\n",
        pixel_t = pixel_type,
    ));

    // Output buffer.
    code.push_str(&format!(
        "    Output<Buffer<{pixel_t}, 3>> output{{\"output\"}};\n\n",
        pixel_t = pixel_type,
    ));

    // GeneratorParams for runtime tuning.
    code.push_str("    // GeneratorParams for auto-tuning\n");
    code.push_str("    GeneratorParam<int> tile_x{\"tile_x\", 256};\n");
    code.push_str("    GeneratorParam<int> tile_y{\"tile_y\", 32};\n\n");

    // generate() method — defines the algorithm.
    code.push_str("    void generate() {\n");
    code.push_str("        Var x(\"x\"), y(\"y\"), c(\"c\");\n");
    code.push_str("        Var xo(\"xo\"), yo(\"yo\"), xi(\"xi\"), yi(\"yi\");\n\n");

    // Clamp input for boundary safety.
    code.push_str("        // Clamp input to handle boundary conditions\n");
    code.push_str("        Func clamped = BoundaryConditions::repeat_edge(input);\n\n");

    // Generate each stage's algorithm.
    let mut prev_func = "clamped".to_string();
    for (i, resolved) in pipeline.stages.iter().enumerate() {
        let func = &resolved.func_name;
        code.push_str(&format!(
            "        // Stage {}: {} ({})\n",
            i + 1,
            func,
            resolved.stage.operation,
        ));

        let algorithm = generate_stage_algorithm(resolved, &prev_func, pixel_type);
        for line in algorithm.lines() {
            code.push_str(&format!("        {}\n", line));
        }
        code.push('\n');
        prev_func = func.clone();
    }

    // Wire last stage to output.
    code.push_str(&format!(
        "        output(x, y, c) = {}(x, y, c);\n",
        prev_func,
    ));
    code.push_str("    }\n\n");

    // schedule() method — defines how computation is mapped to hardware.
    code.push_str("    void schedule() {\n");
    code.push_str("        Var x = output.args()[0];\n");
    code.push_str("        Var y = output.args()[1];\n");
    code.push_str("        Var c = output.args()[2];\n");
    code.push_str("        Var xo, yo, xi, yi;\n\n");

    // Generate schedule for output.
    let output_schedule = generate_output_schedule(manifest, pipeline);
    for line in output_schedule.lines() {
        code.push_str(&format!("        {}\n", line));
    }

    // Generate per-stage schedule.
    for (i, resolved) in pipeline.stages.iter().enumerate() {
        code.push_str(&format!(
            "\n        // Schedule for stage: {}\n",
            resolved.func_name,
        ));
        let stage_sched = generate_stage_schedule(resolved, &pipeline.schedules[i], target);
        for line in stage_sched.lines() {
            code.push_str(&format!("        {}\n", line));
        }
    }

    code.push_str("    }\n");
    code.push_str("};\n\n");

    // Register the generator.
    code.push_str(&format!(
        "HALIDE_REGISTER_GENERATOR({name}Generator, {name}_generator)\n"
    ));

    code
}

/// Generate the Halide algorithm code for a single pipeline stage.
fn generate_stage_algorithm(
    resolved: &ResolvedStage,
    prev_func: &str,
    pixel_type: &PixelType,
) -> String {
    let func = &resolved.func_name;
    let params = &resolved.stage.params;

    match &resolved.stage.operation {
        HalideOperation::Blur => {
            let ks = params.kernel_size.unwrap_or(3);
            let sigma = params.sigma.unwrap_or(1.0);
            let radius = ks as i32 / 2;
            format!(
                "Func {func}(\"{func}\");\n\
                 RDom r(-{radius}, {ks}, -{radius}, {ks});\n\
                 Expr gaussian_weight = exp(-(r.x * r.x + r.y * r.y) / (2.0f * {sigma}f * {sigma}f));\n\
                 {func}(x, y, c) = sum(cast<float>({prev}(x + r.x, y + r.y, c)) * gaussian_weight) / \n\
                                    sum(gaussian_weight);\n\
                 {func}(x, y, c) = cast<{pixel_t}>({func}(x, y, c));",
                func = func,
                radius = radius,
                ks = ks,
                sigma = sigma,
                prev = prev_func,
                pixel_t = pixel_type,
            )
        }
        HalideOperation::Sharpen => {
            let ks = params.kernel_size.unwrap_or(3);
            let radius = ks as i32 / 2;
            format!(
                "Func {func}(\"{func}\");\n\
                 Func {func}_blur(\"{func}_blur\");\n\
                 RDom r(-{radius}, {ks}, -{radius}, {ks});\n\
                 {func}_blur(x, y, c) = sum(cast<float>({prev}(x + r.x, y + r.y, c))) / ({ks} * {ks});\n\
                 // Unsharp mask: original + alpha * (original - blurred)\n\
                 Expr detail = cast<float>({prev}(x, y, c)) - {func}_blur(x, y, c);\n\
                 {func}(x, y, c) = cast<{pixel_t}>(clamp(\n\
                     cast<float>({prev}(x, y, c)) + 1.5f * detail,\n\
                     0.0f, {max_val}f));",
                func = func,
                radius = radius,
                ks = ks,
                prev = prev_func,
                pixel_t = pixel_type,
                max_val = pixel_max_value(pixel_type),
            )
        }
        HalideOperation::Resize => {
            let w = params.width.unwrap_or(640);
            let h = params.height.unwrap_or(480);
            format!(
                "Func {func}(\"{func}\");\n\
                 Expr src_width = input.width();\n\
                 Expr src_height = input.height();\n\
                 Expr scale_x = cast<float>(src_width) / {w}.0f;\n\
                 Expr scale_y = cast<float>(src_height) / {h}.0f;\n\
                 Expr src_x = cast<float>(x) * scale_x;\n\
                 Expr src_y = cast<float>(y) * scale_y;\n\
                 // Bilinear interpolation\n\
                 Expr x0 = cast<int>(floor(src_x));\n\
                 Expr y0 = cast<int>(floor(src_y));\n\
                 Expr fx = src_x - floor(src_x);\n\
                 Expr fy = src_y - floor(src_y);\n\
                 {func}(x, y, c) = cast<{pixel_t}>(\n\
                     cast<float>({prev}(x0, y0, c)) * (1.0f - fx) * (1.0f - fy) +\n\
                     cast<float>({prev}(x0 + 1, y0, c)) * fx * (1.0f - fy) +\n\
                     cast<float>({prev}(x0, y0 + 1, c)) * (1.0f - fx) * fy +\n\
                     cast<float>({prev}(x0 + 1, y0 + 1, c)) * fx * fy);",
                func = func,
                w = w,
                h = h,
                prev = prev_func,
                pixel_t = pixel_type,
            )
        }
        HalideOperation::Convolve => {
            let ks = params.kernel_size.unwrap_or(3);
            let radius = ks as i32 / 2;
            let kernel_values = if let Some(ref k) = params.kernel {
                k.iter()
                    .map(|v: &f64| format!("{:.6}f", v))
                    .collect::<Vec<_>>()
                    .join(", ")
            } else {
                // Default: identity-like kernel (all 1/N^2).
                let val = 1.0 / (ks as f64 * ks as f64);
                (0..ks * ks)
                    .map(|_| format!("{:.6}f", val))
                    .collect::<Vec<_>>()
                    .join(", ")
            };
            format!(
                "Func {func}(\"{func}\");\n\
                 float {func}_kernel_data[] = {{{kernel_values}}};\n\
                 Buffer<float> {func}_kernel({func}_kernel_data, {ks}, {ks});\n\
                 RDom r(0, {ks}, 0, {ks});\n\
                 {func}(x, y, c) = cast<{pixel_t}>(sum(\n\
                     cast<float>({prev}(x + r.x - {radius}, y + r.y - {radius}, c)) *\n\
                     {func}_kernel(r.x, r.y)));",
                func = func,
                kernel_values = kernel_values,
                ks = ks,
                radius = radius,
                prev = prev_func,
                pixel_t = pixel_type,
            )
        }
        HalideOperation::EdgeDetect => {
            // Sobel edge detection.
            format!(
                "Func {func}(\"{func}\");\n\
                 Func {func}_gray(\"{func}_gray\");\n\
                 // Convert to grayscale first if multi-channel\n\
                 {func}_gray(x, y) = 0.299f * cast<float>({prev}(x, y, 0)) +\n\
                                      0.587f * cast<float>({prev}(x, y, 1)) +\n\
                                      0.114f * cast<float>({prev}(x, y, 2));\n\
                 // Sobel kernels\n\
                 Expr gx = -1.0f * {func}_gray(x - 1, y - 1) + 1.0f * {func}_gray(x + 1, y - 1) +\n\
                           -2.0f * {func}_gray(x - 1, y)     + 2.0f * {func}_gray(x + 1, y) +\n\
                           -1.0f * {func}_gray(x - 1, y + 1) + 1.0f * {func}_gray(x + 1, y + 1);\n\
                 Expr gy = -1.0f * {func}_gray(x - 1, y - 1) - 2.0f * {func}_gray(x, y - 1) - 1.0f * {func}_gray(x + 1, y - 1) +\n\
                            1.0f * {func}_gray(x - 1, y + 1) + 2.0f * {func}_gray(x, y + 1) + 1.0f * {func}_gray(x + 1, y + 1);\n\
                 Expr magnitude = sqrt(gx * gx + gy * gy);\n\
                 {func}(x, y, c) = cast<{pixel_t}>(clamp(magnitude, 0.0f, {max_val}f));",
                func = func,
                prev = prev_func,
                pixel_t = pixel_type,
                max_val = pixel_max_value(pixel_type),
            )
        }
        HalideOperation::Threshold => {
            let threshold_val = params.value.unwrap_or(128.0);
            format!(
                "Func {func}(\"{func}\");\n\
                 {func}(x, y, c) = select(\n\
                     cast<float>({prev}(x, y, c)) > {thresh}f,\n\
                     cast<{pixel_t}>({max_val}),\n\
                     cast<{pixel_t}>(0));",
                func = func,
                prev = prev_func,
                thresh = threshold_val,
                pixel_t = pixel_type,
                max_val = pixel_max_value(pixel_type),
            )
        }
        HalideOperation::ColorConvert => {
            let color_space = params.color_space.as_deref().unwrap_or("grayscale");
            match color_space {
                "grayscale" => {
                    format!(
                        "Func {func}(\"{func}\");\n\
                         Expr gray = 0.299f * cast<float>({prev}(x, y, 0)) +\n\
                                     0.587f * cast<float>({prev}(x, y, 1)) +\n\
                                     0.114f * cast<float>({prev}(x, y, 2));\n\
                         {func}(x, y, c) = cast<{pixel_t}>(gray);",
                        func = func,
                        prev = prev_func,
                        pixel_t = pixel_type,
                    )
                }
                "yuv" => {
                    format!(
                        "Func {func}(\"{func}\");\n\
                         Expr r = cast<float>({prev}(x, y, 0));\n\
                         Expr g = cast<float>({prev}(x, y, 1));\n\
                         Expr b = cast<float>({prev}(x, y, 2));\n\
                         Expr yy = 0.299f * r + 0.587f * g + 0.114f * b;\n\
                         Expr u = -0.169f * r - 0.331f * g + 0.500f * b + 128.0f;\n\
                         Expr v = 0.500f * r - 0.419f * g - 0.081f * b + 128.0f;\n\
                         {func}(x, y, c) = cast<{pixel_t}>(select(c == 0, yy, select(c == 1, u, v)));",
                        func = func,
                        prev = prev_func,
                        pixel_t = pixel_type,
                    )
                }
                _ => {
                    format!(
                        "Func {func}(\"{func}\");\n\
                         // Unsupported color space '{}', passing through\n\
                         {func}(x, y, c) = {prev}(x, y, c);",
                        color_space,
                        func = func,
                        prev = prev_func,
                    )
                }
            }
        }
    }
}

/// Generate the schedule directives for the output Func.
fn generate_output_schedule(manifest: &Manifest, _pipeline: &ResolvedPipeline) -> String {
    let target = &manifest.target.arch;
    let vec_width = target.natural_vector_width();

    let mut sched = String::new();
    sched.push_str("// Output schedule\n");

    match target {
        HardwareTarget::Cuda | HardwareTarget::Opencl => {
            sched.push_str("Var block_x, block_y, thread_x, thread_y;\n");
            sched
                .push_str("output.gpu_tile(x, y, block_x, block_y, thread_x, thread_y, 32, 32);\n");
        }
        _ => {
            sched.push_str("output\n");
            sched.push_str("    .tile(x, y, xo, yo, xi, yi, tile_x, tile_y)\n");
            if manifest.target.vectorize {
                sched.push_str(&format!("    .vectorize(xi, {})\n", vec_width,));
            }
            if manifest.target.parallelize {
                sched.push_str("    .parallel(yo);\n");
            } else {
                // Remove trailing newline and add semicolon.
                sched.push_str("    ;\n");
            }
        }
    }

    sched
}

/// Generate schedule code for a single pipeline stage.
fn generate_stage_schedule(
    resolved: &ResolvedStage,
    schedule_primitives: &[SchedulePrimitive],
    target: &HardwareTarget,
) -> String {
    let func = &resolved.func_name;
    let mut sched = String::new();

    match target {
        HardwareTarget::Cuda | HardwareTarget::Opencl => {
            // For GPU targets, compute each stage inline at the output's GPU tiles.
            sched.push_str(&format!("{func}.compute_at(output, block_x);\n"));
        }
        _ => {
            // For CPU targets, compute at the output's outer tile dimension.
            sched.push_str(&format!("{func}.compute_at(output, yo);\n"));
            // Apply vectorization if present in the schedule.
            for prim in schedule_primitives {
                if let SchedulePrimitive::Vectorize { width } = prim {
                    sched.push_str(&format!(
                        "{func}.vectorize({func}.args()[0], {width});\n",
                        func = func,
                        width = width,
                    ));
                    break;
                }
            }
        }
    }

    sched
}

/// Return the maximum pixel value for a given pixel type (used in clamp expressions).
fn pixel_max_value(pixel_type: &PixelType) -> f64 {
    match pixel_type {
        PixelType::Uint8 => 255.0,
        PixelType::Uint16 => 65535.0,
        PixelType::Float32 => 1.0,
        PixelType::Float64 => 1.0,
    }
}

// ---------------------------------------------------------------------------
// Runner C++ source
// ---------------------------------------------------------------------------

/// Generate a standalone runner that loads an image, runs the pipeline, and
/// saves the output. Uses Halide's `load_image` / `save_image` helpers.
pub fn generate_runner(manifest: &Manifest) -> String {
    let name = &manifest.project.name;
    let pixel_type = &manifest.pipeline.bit_depth;

    let mut code = String::with_capacity(2048);

    code.push_str(&format!(
        "// Auto-generated runner for {} — DO NOT EDIT\n",
        name
    ));
    code.push_str("// SPDX-License-Identifier: PMPL-1.0-or-later\n\n");
    code.push_str("#include \"HalideBuffer.h\"\n");
    code.push_str("#include \"halide_image_io.h\"\n");
    code.push_str(&format!("#include \"{name}_generator.h\"\n\n"));
    code.push_str("#include <cstdio>\n");
    code.push_str("#include <cstdlib>\n\n");

    code.push_str("int main(int argc, char **argv) {\n");
    code.push_str("    if (argc < 3) {\n");
    code.push_str(&format!(
        "        fprintf(stderr, \"Usage: %s <input.{in_fmt}> <output.{out_fmt}>\\n\", argv[0]);\n",
        in_fmt = manifest.pipeline.input_format,
        out_fmt = manifest.pipeline.output_format,
    ));
    code.push_str("        return 1;\n");
    code.push_str("    }\n\n");

    code.push_str(&format!(
        "    Halide::Runtime::Buffer<{pixel_t}> input = \n\
         \x20       Halide::Tools::load_image(argv[1]);\n\n",
        pixel_t = pixel_type,
    ));

    code.push_str(&format!(
        "    Halide::Runtime::Buffer<{pixel_t}> output(\n\
         \x20       input.width(), input.height(), input.channels());\n\n",
        pixel_t = pixel_type,
    ));

    code.push_str(&format!(
        "    int error = {name}_generator(input, output);\n",
    ));
    code.push_str("    if (error) {\n");
    code.push_str("        fprintf(stderr, \"Pipeline failed with error %d\\n\", error);\n");
    code.push_str("        return error;\n");
    code.push_str("    }\n\n");

    code.push_str("    Halide::Tools::save_image(output, argv[2]);\n");
    code.push_str(&format!(
        "    printf(\"{name} pipeline completed: %s -> %s\\n\", argv[1], argv[2]);\n",
    ));
    code.push_str("    return 0;\n");
    code.push_str("}\n");

    code
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::codegen::parser::resolve_pipeline;
    use crate::manifest::parse_manifest;

    #[test]
    fn test_generate_blur_pipeline() {
        let toml_str = r#"
[project]
name = "blur_test"

[[stages]]
name = "gauss"
operation = "blur"
kernel-size = 5
sigma = 1.4

[target]
arch = "x86"

[pipeline]
input-format = "png"
output-format = "png"
"#;
        let m = parse_manifest(toml_str).expect("TODO: handle error");
        let resolved = resolve_pipeline(&m).expect("TODO: handle error");
        let code = generate_halide_generator(&m, &resolved);
        assert!(code.contains("class blur_testGenerator"));
        assert!(code.contains("RDom r("));
        assert!(code.contains("gaussian_weight"));
        assert!(code.contains("HALIDE_REGISTER_GENERATOR"));
    }

    #[test]
    fn test_generate_runner() {
        let toml_str = r#"
[project]
name = "runner_test"

[[stages]]
name = "sharp"
operation = "sharpen"

[target]
arch = "arm"

[pipeline]
input-format = "jpg"
output-format = "png"
"#;
        let m = parse_manifest(toml_str).expect("TODO: handle error");
        let runner = generate_runner(&m);
        assert!(runner.contains("runner_test_generator.h"));
        assert!(runner.contains("input.jpg"));
        assert!(runner.contains("output.png"));
        assert!(runner.contains("int main("));
    }

    #[test]
    fn test_generate_edge_detect_contains_sobel() {
        let toml_str = r#"
[project]
name = "edge_test"

[[stages]]
name = "edges"
operation = "edge-detect"

[target]
arch = "x86"

[pipeline]
input-format = "png"
output-format = "png"
"#;
        let m = parse_manifest(toml_str).expect("TODO: handle error");
        let resolved = resolve_pipeline(&m).expect("TODO: handle error");
        let code = generate_halide_generator(&m, &resolved);
        assert!(code.contains("Sobel"));
        assert!(code.contains("gx"));
        assert!(code.contains("gy"));
        assert!(code.contains("magnitude"));
    }

    #[test]
    fn test_generate_cuda_uses_gpu_tile() {
        let toml_str = r#"
[project]
name = "gpu_test"

[[stages]]
name = "blur_gpu"
operation = "blur"
kernel-size = 3

[target]
arch = "cuda"

[pipeline]
input-format = "raw"
output-format = "raw"
bit-depth = "float32"
"#;
        let m = parse_manifest(toml_str).expect("TODO: handle error");
        let resolved = resolve_pipeline(&m).expect("TODO: handle error");
        let code = generate_halide_generator(&m, &resolved);
        assert!(code.contains("gpu_tile"));
        assert!(code.contains("block_x"));
    }

    #[test]
    fn test_pixel_max_values() {
        assert_eq!(pixel_max_value(&PixelType::Uint8), 255.0);
        assert_eq!(pixel_max_value(&PixelType::Uint16), 65535.0);
        assert_eq!(pixel_max_value(&PixelType::Float32), 1.0);
    }
}
